dbus-sysdeps-unix.c
O_BINARY
AI_ADDRCONFIG
socklen_t
_DBUS_MAX_SUN_PATH_LENGTH
Maximum length of the path to a UNIX domain socket, sockaddr_un::sun_path member.
POSIX requires that all systems support at least 100 bytes here, including the nul termination. We use 99 for the max value to allow for the nul.We could probably also do sizeof (addr.sun_path) but this way we are the same on all platforms which is probably a good idea.
NANOSECONDS_PER_SECOND
nanoseconds in a second
MICROSECONDS_PER_SECOND
microseconds in a second
MILLISECONDS_PER_SECOND
milliseconds in a second
NANOSECONDS_PER_MILLISECOND
nanoseconds in a millisecond
MICROSECONDS_PER_MILLISECOND
microseconds in a millisecond
pthread_mutex_t atomic_mutex
dbus_bool_t _dbus_ensure_standard_fds(DBusEnsureStandardFdsFlags flags, const char **error_str_p)
Ensure that the standard file descriptors stdin, stdout and stderr are open, by opening /dev/null if necessary.
This function does not use DBusError, to avoid calling malloc(), so that it can be used in contexts where an async-signal-safe function is required (for example after fork()). Instead, on failure it sets errno and returns something like "Failed to open /dev/null" in *error_str_p. Callers are expected to combine *error_str_p with _dbus_strerror (errno) to get a full error report.This function can only be called while single-threaded: either during startup of an executable, or after fork().
static dbus_bool_t _dbus_set_fd_nonblocking(int fd, DBusError *error)
static dbus_bool_t _dbus_open_socket(int *fd_p, int domain, int type, int protocol, DBusError *error)
static dbus_bool_t _dbus_open_unix_socket(int *fd, DBusError *error)
Opens a UNIX domain socket (as in the socket() call).
Does not bind the socket.This will set FD_CLOEXEC for the socket returned fd return location for socket descriptor error return location for an error FALSE if error is set
dbus_bool_t _dbus_close_socket(DBusSocket fd, DBusError *error)
Closes a socket.
Should not be used on non-socket file descriptors or handles. fd the socket error return location for an error FALSE if error is set
Referenced by _dbus_server_new_for_tcp_socket, _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket.
int _dbus_read_socket(DBusSocket fd, DBusString *buffer, int count)
Like _dbus_read(), but only works on sockets so is available on Windows.
fd the socket buffer string to append data to count max amount of data to read number of bytes appended to the string
Referenced by _dbus_read_socket_with_unix_fds.
int _dbus_write_socket(DBusSocket fd, const DBusString *buffer, int start, int len)
Like _dbus_write(), but only supports sockets and is thus available on Windows.
fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error
int _dbus_read_socket_with_unix_fds(DBusSocket fd, DBusString *buffer, int count, int *fds, int *n_fds)
Like _dbus_read_socket() but also tries to read unix fds from the socket.
When there are more fds to read than space in the array passed this function will fail with ENOSPC. fd the socket buffer string to append data to count max amount of data to read fds array to place read file descriptors in n_fds on input space in fds array, on output how many fds actually got read number of bytes appended to string
References _dbus_read_socket, _dbus_assert, _dbus_string_lengthen, _DBUS_ZERO, _dbus_string_get_data_len, _dbus_string_set_length, FALSE.
int _dbus_write_socket_with_unix_fds(DBusSocket fd, const DBusString *buffer, int start, int len, const int *fds, int n_fds)
int _dbus_write_socket_with_unix_fds_two(DBusSocket fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2, const int *fds, int n_fds)
int _dbus_write_socket_two(DBusSocket fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2)
Like _dbus_write_two() but only works on sockets and is thus available on Windows.
fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error
int _dbus_read(int fd, DBusString *buffer, int count)
Thin wrapper around the read() system call that appends the data it reads to the DBusString buffer.
It appends up to the given count, and returns the same value and same errno as read(). The only exception is that _dbus_read() handles EINTR for you. Also, _dbus_read() can return ENOMEM, even though regular UNIX read doesn't.Unlike _dbus_read_socket(), _dbus_read() is not available on Windows. fd the file descriptor to read from buffer the buffer to append data to count the amount of data to read the number of bytes read or -1
References _dbus_assert, _dbus_string_lengthen, _dbus_string_get_data_len, _dbus_string_set_length, _dbus_verbose_bytes_of_string.
Referenced by _dbus_file_get_contents, _dbus_read_socket, _dbus_generate_random_bytes, _dbus_get_tmpdir, _dbus_command_for_pid.
int _dbus_write(int fd, const DBusString *buffer, int start, int len)
Thin wrapper around the write() system call that writes a part of a DBusString and handles EINTR for you.
fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error
References _dbus_verbose_bytes_of_string.
Referenced by _dbus_string_save_to_file, _dbus_write_socket, _dbus_write_two.
int _dbus_write_two(int fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2)
Like _dbus_write() but will use writev() if possible to write both buffers in sequence.
The return value is the number of bytes written in the first buffer, plus the number written in the second. If the first buffer is written successfully and an error occurs writing the second, the number of bytes in the first is returned (i.e. the error is ignored), on systems that don't have writev. Handles EINTR for you. The second buffer may be NULL. fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error
References _dbus_assert, NULL, _dbus_write.
Referenced by _dbus_write_socket_two.
int _dbus_connect_unix_socket(const char *path, dbus_bool_t abstract, DBusError *error)
Creates a socket and connects it to the UNIX domain socket at the given path.
The connection fd is returned, and is set up as nonblocking.Uses abstract sockets instead of filesystem-linked sockets if requested (it's possible only on Linux; see "man 7 unix" on Linux). On non-Linux abstract socket usage always fails.This will set FD_CLOEXEC for the socket returned. path the path to UNIX domain socket abstract TRUE to use abstract namespace error return location for error code connection file descriptor or -1 on error
References _DBUS_ZERO, dbus_set_error, DBUS_ERROR_BAD_ADDRESS, _dbus_close, NULL, DBUS_ERROR_NOT_SUPPORTED, _dbus_error_from_errno.
int _dbus_connect_exec(const char *path, char *const argv[], DBusError *error)
Creates a UNIX domain socket and connects it to the specified process to execute.
This will set FD_CLOEXEC for the socket returned. path the path to the executable argv the argument list for the process to execute. argv[0] typically is identical to the path of the executable error return location for error code connection file descriptor or -1 on error
References dbus_set_error, _dbus_error_from_errno, _dbus_fd_set_close_on_exec, _dbus_close_all.
int _dbus_listen_unix_socket(const char *path, dbus_bool_t abstract, DBusError *error)
Creates a socket and binds it to the given path, then listens on the socket.
The socket is set to be nonblocking.Uses abstract sockets instead of filesystem-linked sockets if requested (it's possible only on Linux; see "man 7 unix" on Linux). On non-Linux abstract socket usage always fails.This will set FD_CLOEXEC for the socket returned path the socket name abstract TRUE to use abstract namespace error return location for errors the listening file descriptor or -1 on error
References _DBUS_ZERO, dbus_set_error, DBUS_ERROR_BAD_ADDRESS, _dbus_close, NULL, DBUS_ERROR_NOT_SUPPORTED, _dbus_error_from_errno, _dbus_warn.
Referenced by _dbus_server_new_for_domain_socket.
int _dbus_listen_systemd_sockets(DBusSocket **fds, DBusError *error)
Acquires one or more sockets passed in from systemd.
The sockets are set to be nonblocking.This will set FD_CLOEXEC for the sockets returned. fds the file descriptors error return location for errors the number of file descriptors
References TRUE, dbus_set_error, _dbus_error_from_errno, DBUS_ERROR_BAD_ADDRESS, dbus_new, DBUS_ERROR_NO_MEMORY, _dbus_close, NULL, dbus_free, dbus_set_error_const, DBUS_ERROR_NOT_SUPPORTED.
Referenced by _dbus_server_listen_platform_specific.
DBusSocket _dbus_connect_tcp_socket(const char *host, const char *port, const char *family, DBusError *error)
Creates a socket and connects to a socket at the given host and port.
The connection fd is returned, and is set up as nonblocking.This will set FD_CLOEXEC for the socket returned host the host name to connect to port the port to connect to family the address family to listen on, NULL for all error return location for error code connection file descriptor or -1 on error
DBusSocket _dbus_connect_tcp_socket_with_nonce(const char *host, const char *port, const char *family, const char *noncefile, DBusError *error)
int _dbus_listen_tcp_socket(const char *host, const char *port, const char *family, DBusString *retport, DBusSocket **fds_p, DBusError *error)
Creates a socket and binds it to the given path, then listens on the socket.
The socket is set to be nonblocking. In case of port=0 a random free port is used and returned in the port parameter. If inaddr_any is specified, the hostname is ignored.This will set FD_CLOEXEC for the socket returned host the host name to listen on port the port to listen on, if zero a free port will be used family the address family to listen on, NULL for all retport string to return the actual port listened on fds_p location to store returned file descriptors error return location for errors the number of listening file descriptors or -1 on error
Referenced by _dbus_server_new_for_tcp_socket.
static dbus_bool_t write_credentials_byte(int server_fd, DBusError *error)
static dbus_bool_t add_linux_security_label_to_credentials(int client_fd, DBusCredentials *credentials)
dbus_bool_t _dbus_read_credentials_socket(DBusSocket client_fd, DBusCredentials *credentials, DBusError *error)
Reads a single byte which must be nul (an error occurs otherwise), and reads unix credentials if available.
Clears the credentials object, then adds pid/uid if available, so any previous credentials stored in the object are lost.DBusServer makes the security assumption that the credentials returned by this method are the credentials that were active at the time the socket was opened. Do not add APIs to this method that would break that assumption.In particular, it is incorrect to use any API of the form "get the process ID at the other end of the connection, then determine its uid, gid, or other credentials from the pid" (e.g. looking in /proc on Linux). If we did that, we would be vulnerable to several attacks. A malicious process could queue up the rest of the authentication handshake and a malicious message that it should not be allowed to send, then race with the DBusServer to exec() a more privileged (e.g. setuid) binary that would have been allowed to send that message; or it could exit, and arrange for enough setuid processes to be started that its pid would be recycled for one of those processes with high probability; or it could fd-pass the connection to a more privileged process.Return value indicates whether a byte was read, not whether we got valid credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte is available, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. client_fd the client file descriptor credentials object to add client credentials to error location to store error code TRUE on success
dbus_bool_t _dbus_send_credentials_socket(DBusSocket server_fd, DBusError *error)
Sends a single nul byte with our UNIX credentials as ancillary data.
Returns TRUE if the data was successfully written. On systems that don't support sending credentials, just writes a byte, doesn't send any credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte can be written, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. server_fd file descriptor for connection to server error return location for error code TRUE if the byte was sent
DBusSocket _dbus_accept(DBusSocket listen_fd)
Accepts a connection on a listening socket.
Handles EINTR for you.This will enable FD_CLOEXEC for the returned socket. listen_fd the listen file descriptor the connection fd of the client, or -1 on error
dbus_bool_t _dbus_check_dir_is_private_to_user(DBusString *dir, DBusError *error)
Checks to make sure the given directory is private to the user.
dir the name of the directory error error return FALSE on failure
static dbus_bool_t fill_user_info_from_passwd(struct passwd *p, DBusUserInfo *info, DBusError *error)
static dbus_bool_t fill_user_info(DBusUserInfo *info, dbus_uid_t uid, const DBusString *username, DBusError *error)
dbus_bool_t _dbus_user_info_fill(DBusUserInfo *info, const DBusString *username, DBusError *error)
Gets user info for the given username.
info user info object to initialize username the username error error return TRUE on success
References DBUS_UID_UNSET.
Referenced by _dbus_user_database_lookup.
dbus_bool_t _dbus_user_info_fill_uid(DBusUserInfo *info, dbus_uid_t uid, DBusError *error)
Gets user info for the given user ID.
info user info object to initialize uid the user ID error error return TRUE on success
References NULL.
Referenced by _dbus_user_database_lookup.
dbus_bool_t _dbus_credentials_add_from_current_process(DBusCredentials *credentials)
Adds the credentials of the current process to the passed-in credentials object.
credentials credentials to add to FALSE if no memory; does not properly roll back on failure, so only some credentials may have been added
Referenced by _dbus_credentials_new_from_current_process, _dbus_keyring_new_for_credentials.
dbus_bool_t _dbus_append_user_from_current_process(DBusString *str)
Append to the string the identity we would like to have when we authenticate, on UNIX this is the current process UID and on Windows something else, probably a Windows SID string.
No escaping is required, that is done in dbus-auth.c. The username here need not be anything human-readable, it can be the machine-readable form i.e. a user id. str the string to append to FALSE on no memory
dbus_pid_t _dbus_getpid(void)
Gets our process ID.
process ID
dbus_uid_t _dbus_getuid(void)
Gets our UID.
process UID
dbus_uid_t _dbus_geteuid(void)
Gets our effective UID.
process effective UID
Referenced by _dbus_append_user_from_current_process, _dbus_unix_user_is_process_owner.
unsigned long _dbus_pid_for_log(void)
The only reason this is separate from _dbus_getpid() is to allow it on Windows for logging but not for other purposes.
process ID to put in log messages
Referenced by _dbus_real_assert, _dbus_real_assert_not_reached, _dbus_abort.
dbus_bool_t _dbus_parse_uid(const DBusString *uid_str, dbus_uid_t *uid)
Gets a UID from a UID string.
uid_str the UID in string form uid UID to fill in TRUE if successfully filled in UID
References FALSE, _dbus_string_parse_int, TRUE.
dbus_int32_t _dbus_atomic_inc(DBusAtomic *atomic)
Atomically increments an integer.
atomic pointer to the integer to increment the value before incrementing
Referenced by _dbus_connection_ref_unlocked, dbus_connection_ref, dbus_connection_add_filter, dbus_malloc, dbus_malloc0, dbus_realloc, dbus_message_copy, dbus_message_ref, _dbus_pending_call_ref_unlocked, dbus_pending_call_ref, _dbus_server_init_base, _dbus_server_ref_unlocked, dbus_server_ref, dbus_server_unref, _dbus_babysitter_ref.
dbus_int32_t _dbus_atomic_dec(DBusAtomic *atomic)
Atomically decrement an integer.
atomic pointer to the integer to decrement the value before decrementing
Referenced by _dbus_connection_unref_unlocked, dbus_connection_unref, dbus_free, dbus_message_unref, _dbus_pending_call_unref_and_unlock, dbus_pending_call_unref, _dbus_server_unref_unlocked, dbus_server_ref, dbus_server_unref, _dbus_babysitter_unref.
dbus_int32_t _dbus_atomic_get(DBusAtomic *atomic)
Atomically get the value of an integer.
It may change at any time thereafter, so this is mostly only useful for assertions. atomic pointer to the integer to get the value at this moment
Referenced by _dbus_connection_close_if_only_one_ref.
int _dbus_poll(DBusPollFD *fds, int n_fds, int timeout_milliseconds)
Wrapper for poll().
fds the file descriptors to poll n_fds number of descriptors in the array timeout_milliseconds timeout or -1 for infinite numbers of fds with revents, or <0 on error
void _dbus_get_monotonic_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Use the monotonic clock if available, to avoid problems when the system time changes. tv_sec return location for number of seconds tv_usec return location for number of microseconds
void _dbus_get_real_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Never uses the monotonic clock. tv_sec return location for number of seconds tv_usec return location for number of microseconds
Referenced by _dbus_generate_uuid.
dbus_bool_t _dbus_create_directory(const DBusString *filename, DBusError *error)
Creates a directory; succeeds if the directory is created or already existed.
directory interface filename directory filename error initialized error object TRUE on success
dbus_bool_t _dbus_concat_dir_and_file(DBusString *dir, const DBusString *next_component)
Appends the given filename to the given directory.
Todoit might be cute to collapse multiple '/' such as "foo//" concat "//bar" dir the directory name next_component the filename TRUE on success
Referenced by _dbus_server_listen_platform_specific, _dbus_sha_compute, _dbus_append_keyring_directory_for_credentials, _dbus_user_at_console, _dbus_get_standard_session_servicedirs, _dbus_get_standard_system_servicedirs, _dbus_split_paths_and_append.
void _dbus_sleep_milliseconds(int milliseconds)
Sleeps the given number of milliseconds.
milliseconds number of milliseconds
Referenced by _dbus_abort.
dbus_bool_t _dbus_generate_random_bytes(DBusString *str, int n_bytes, DBusError *error)
Generates the given number of securely random bytes, using the best mechanism we can come up with.
str the string n_bytes the number of random bytes to append to string error location to store reason for failure TRUE on success, FALSE on error
Referenced by _dbus_generate_random_bytes_buffer, _dbus_generate_random_ascii.
void _dbus_exit(int code)
Exit the process, returning the given value.
code the exit code
Referenced by _dbus_abort.
const char* _dbus_strerror(int error_number)
A wrapper around strerror() because some platforms may be lame and not have strerror().
Also, never returns NULL. error_number errno. error description.
void _dbus_disable_sigpipe(void)
signal (SIGPIPE, SIG_IGN);
void _dbus_fd_set_close_on_exec(int fd)
Sets the file descriptor to be close on exec.
Should be called for all file descriptors in D-Bus code. fd the file descriptor
Referenced by _dbus_server_new_for_launchd, _dbus_connect_exec, _dbus_accept, _dbus_dup, _dbus_socketpair.
dbus_bool_t _dbus_close(int fd, DBusError *error)
Closes a file descriptor.
fd the file descriptor error error object FALSE if error set
References dbus_set_error, _dbus_error_from_errno, FALSE, TRUE.
Referenced by _dbus_file_get_contents, _dbus_string_save_to_file, _dbus_create_file_exclusively, _dbus_close_socket, _dbus_connect_unix_socket, _dbus_listen_unix_socket, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_generate_random_bytes, _dbus_socketpair, _dbus_command_for_pid.
int _dbus_dup(int fd, DBusError *error)
Duplicates a file descriptor.
Makes sure the fd returned is >= 3 (i.e. avoids stdin/stdout/stderr). Sets O_CLOEXEC. fd the file descriptor to duplicate error address of error location. duplicated file descriptor
References dbus_set_error, _dbus_error_from_errno, _dbus_fd_set_close_on_exec.
Referenced by dbus_message_copy, dbus_message_iter_get_basic.
dbus_bool_t _dbus_set_socket_nonblocking(DBusSocket fd, DBusError *error)
Sets a file descriptor to be nonblocking.
fd the file descriptor. error address of error location. TRUE on success.
void _dbus_print_backtrace(void)
On GNU libc systems, print a crude backtrace to stderr.
On other systems, print "no backtrace support" and block for possible gdb attachment if an appropriate environment variable is set.
Referenced by _dbus_abort.
dbus_bool_t _dbus_socketpair(DBusSocket *fd1, DBusSocket *fd2, dbus_bool_t blocking, DBusError *error)
Creates pair of connect sockets (as in socketpair()).
Sets both ends of the pair nonblocking.Marks both file descriptors as close-on-exec fd1 return location for one end fd2 return location for the other end blocking TRUE if pair should be blocking error error return FALSE on failure (if error is set)
int _dbus_printf_string_upper_bound(const char *format, va_list args)
Measure the length of the given format string and arguments, not including the terminating nul.
format a printf-style format string args arguments for the format string length of the given format string and args, or -1 if no memory
const char* _dbus_get_tmpdir(void)
Gets the temporary files directory by inspecting the environment variables TMPDIR, TMP, and TEMP in that order.
If none of those are set "/tmp" is returnedlocation of temp directory, or NULL if no memory for locking
dbus_bool_t _dbus_get_autolaunch_address(const char *scope, DBusString *address, DBusError *error)
Returns the address of a new session bus.
If successful, returns TRUE and appends the address to address. If a failure happens, returns FALSE and sets an error in error. scope scope of autolaunch (Windows only) address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
dbus_bool_t _dbus_read_local_machine_uuid(DBusGUID *machine_id, dbus_bool_t create_if_not_found, DBusError *error)
Reads the uuid of the machine we're running on from the dbus configuration.
Optionally try to create it (only root can do this usually).On UNIX, reads a file that gets created by dbus-uuidgen in a post-install script. On Windows, if there's a standard machine uuid we could just use that, but I can't find one with the right properties (the hardware profile guid can change without rebooting I believe). If there's no standard one we might want to use the registry instead of a file for this, and I'm not sure how we'd ensure the uuid gets created. machine_id guid to init with the machine's uuid create_if_not_found try to create the uuid if it doesn't exist error the error return FALSE if the error is set
Referenced by dbus_internal_do_not_use_get_uuid.
dbus_bool_t _dbus_lookup_launchd_socket(DBusString *socket_path, const char *launchd_env_var, DBusError *error)
quries launchd for a specific env var which holds the socket path.
socket_path append the socket path to this DBusString launchd_env_var the env var to look up error a DBusError to store the error in case of failure the value of the env var
References _dbus_check_setuid, dbus_set_error_const, DBUS_ERROR_NOT_SUPPORTED, FALSE, NULL, _dbus_assert, _DBUS_N_ELEMENTS, TRUE, _dbus_string_shorten, dbus_set_error, _dbus_string_init, _dbus_lookup_launchd_socket, dbus_error_is_set, _dbus_string_free, _dbus_string_append, _dbus_string_copy.
Referenced by _dbus_lookup_launchd_socket.
dbus_bool_t _dbus_lookup_user_bus(dbus_bool_t *supported, DBusString *address, DBusError *error)
dbus_bool_t _dbus_lookup_session_address(dbus_bool_t *supported, DBusString *address, DBusError *error)
Determines the address of the session bus by querying a platform-specific method.
The first parameter will be a boolean specifying whether or not a dynamic session lookup is supported on this platform.If supported is TRUE and the return value is TRUE, the address will be appended to address. If a failure happens, returns FALSE and sets an error in error.If supported is FALSE, ignore the return value. supported returns whether this method is supported address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
void _dbus_flush_caches(void)
Called when the bus daemon is signaled to reload its configuration; any caches should be nuked.
Of course any caches that need explicit reload are probably broken, but c'est la vie.
dbus_bool_t _dbus_append_keyring_directory_for_credentials(DBusString *directory, DBusCredentials *credentials)
Appends the directory in which a keyring for the given credentials should be stored.
The credentials should have either a Windows or UNIX user in them. The directory should be an absolute path.On UNIX the directory is ~/.dbus-keyrings while on Windows it should probably be something else, since the dotfile convention is not normal on Windows. directory string to append directory to credentials credentials the directory should be for FALSE on no memory
Referenced by _dbus_keyring_new_for_credentials.
dbus_bool_t _dbus_daemon_publish_session_bus_address(const char *addr, const char *scope)
void _dbus_daemon_unpublish_session_bus_address(void)
dbus_bool_t _dbus_get_is_errno_eagain_or_ewouldblock(int e)
See if errno is EAGAIN or EWOULDBLOCK (this has to be done differently for Winsock so is abstracted)
TRUE if e == EAGAIN or e == EWOULDBLOCK
dbus_bool_t _dbus_delete_directory(const DBusString *filename, DBusError *error)
Removes a directory; Directory must be empty.
filename directory filename error initialized error object TRUE on success
dbus_bool_t _dbus_socket_can_pass_unix_fd(DBusSocket fd)
Checks whether file descriptors may be passed via the socket.
fd the socket TRUE when fd passing over this socket is supported
References _DBUS_ZERO, FALSE.
void _dbus_close_all(void)
Closes all file descriptors except the first three (i.e.
stdin, stdout, stderr).
References NULL.
Referenced by _dbus_connect_exec, _dbus_get_tmpdir.
dbus_bool_t _dbus_check_setuid(void)
NOTE: If you modify this function, please also consider making the corresponding change in GLib.
See glib/gutils.c:g_check_setuid().Returns TRUE if the current process was executed as setuid (or an equivalent __libc_enable_secure is available). See: http://osdir.com/ml/linux.lfs.hardened/2007-04/msg00032.html
Referenced by _dbus_keyring_new_for_credentials, _dbus_threads_init_platform_specific, _dbus_get_autolaunch_address, _dbus_lookup_launchd_socket, _dbus_getenv.
dbus_bool_t _dbus_append_address_from_socket(DBusSocket fd, DBusString *address, DBusError *error)
Read the address from the socket and append it to the string.
fd the socket address error return location for error code
References _dbus_string_init_const, _dbus_string_append, _dbus_address_append_escaped, TRUE, _dbus_string_append_printf, dbus_set_error, _dbus_error_from_errno, FALSE.
Referenced by _dbus_server_listen_platform_specific.
int _dbus_save_socket_errno(void)
void _dbus_restore_socket_errno(int saved_errno)