dbus-credentials.h
DBusCredentialType
DBUS_PRIVATE_EXPORT DBusCredentials* _dbus_credentials_new_from_current_process(void)
Creates a new object with credentials (user ID and process ID) from the current process.
the new object or NULL if no memory
References _dbus_credentials_new, NULL, _dbus_credentials_add_from_current_process, _dbus_credentials_unref.
Referenced by _dbus_keyring_new_for_credentials.
DBUS_PRIVATE_EXPORT DBusCredentials* _dbus_credentials_new(void)
Creates a new credentials object.
the new object or NULL if no memory
References dbus_new, NULL, DBUS_UID_UNSET, DBUS_PID_UNSET.
Referenced by _dbus_credentials_new_from_current_process, _dbus_transport_init_base.
DBUS_PRIVATE_EXPORT void _dbus_credentials_ref(DBusCredentials *credentials)
Increment refcount on credentials.
credentials the object
References _dbus_assert.
DBUS_PRIVATE_EXPORT void _dbus_credentials_unref(DBusCredentials *credentials)
Decrement refcount on credentials.
credentials the object
References _dbus_assert, dbus_free.
Referenced by _dbus_credentials_new_from_current_process, _dbus_keyring_unref, _dbus_transport_init_base, _dbus_transport_finalize_base.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_add_pid(DBusCredentials *credentials, dbus_pid_t pid)
Add a UNIX process ID to the credentials.
credentials the object pid the process ID FALSE if no memory
References TRUE.
Referenced by _dbus_credentials_add_credential, _dbus_read_credentials_socket, _dbus_credentials_add_from_current_process.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_add_unix_uid(DBusCredentials *credentials, dbus_uid_t uid)
Add a UNIX user ID to the credentials.
credentials the object uid the user ID FALSE if no memory
References TRUE.
Referenced by _dbus_credentials_add_credential, _dbus_credentials_add_from_user.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_add_windows_sid(DBusCredentials *credentials, const char *windows_sid)
Add a Windows user SID to the credentials.
credentials the object windows_sid the user SID FALSE if no memory
Referenced by _dbus_credentials_add_credential, _dbus_read_credentials_socket, _dbus_credentials_add_from_user, _dbus_credentials_add_from_current_process.
dbus_bool_t _dbus_credentials_add_linux_security_label(DBusCredentials *credentials, const char *label)
Add a Linux security label, as used by LSMs such as SELinux, Smack and AppArmor, to the credentials.
credentials the object label the label FALSE if no memory
Referenced by _dbus_credentials_add_credential, _dbus_listen_tcp_socket.
dbus_bool_t _dbus_credentials_add_adt_audit_data(DBusCredentials *credentials, void *audit_data, dbus_int32_t size)
Add ADT audit data to the credentials.
credentials the object audit_data the audit data size the length of audit data FALSE if no memory
Referenced by _dbus_credentials_add_credential.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_include(DBusCredentials *credentials, DBusCredentialType type)
Checks whether the given credential is present.
credentials the object type the credential to check for TRUE if the credential is present
References DBUS_PID_UNSET, DBUS_UID_UNSET, NULL, _dbus_assert_not_reached, FALSE.
Referenced by _dbus_transport_try_to_authenticate, _dbus_transport_get_unix_user, _dbus_transport_get_unix_process_id, _dbus_transport_get_adt_audit_session_data, _dbus_transport_get_windows_user.
DBUS_PRIVATE_EXPORT dbus_pid_t _dbus_credentials_get_pid(DBusCredentials *credentials)
Gets the UNIX process ID in the credentials, or DBUS_PID_UNSET if the credentials object doesn't contain a process ID.
credentials the object UNIX process ID
Referenced by _dbus_transport_get_unix_process_id.
DBUS_PRIVATE_EXPORT dbus_uid_t _dbus_credentials_get_unix_uid(DBusCredentials *credentials)
Gets the UNIX user ID in the credentials, or DBUS_UID_UNSET if the credentials object doesn't contain a user ID.
credentials the object UNIX user ID
Referenced by _dbus_append_keyring_directory_for_credentials, _dbus_transport_get_unix_user.
DBUS_PRIVATE_EXPORT const char* _dbus_credentials_get_windows_sid(DBusCredentials *credentials)
Gets the Windows user SID in the credentials, or NULL if the credentials object doesn't contain a Windows user SID.
credentials the object Windows user SID
Referenced by _dbus_transport_get_windows_user.
const char* _dbus_credentials_get_linux_security_label(DBusCredentials *credentials)
Gets the Linux security label (as used by LSMs) from the credentials, or NULL if the credentials object doesn't contain a security label.
credentials the object the security label
void* _dbus_credentials_get_adt_audit_data(DBusCredentials *credentials)
Gets the ADT audit data in the credentials, or NULL if the credentials object doesn't contain ADT audit data.
credentials the object Solaris ADT audit data
Referenced by _dbus_transport_get_adt_audit_session_data.
dbus_int32_t _dbus_credentials_get_adt_audit_data_size(DBusCredentials *credentials)
Gets the ADT audit data size in the credentials, or 0 if the credentials object doesn't contain ADT audit data.
credentials the object Solaris ADT audit data size
Referenced by _dbus_transport_get_adt_audit_session_data.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_are_superset(DBusCredentials *credentials, DBusCredentials *possible_subset)
Checks whether the first credentials object contains all the credentials found in the second credentials object.
credentials the object possible_subset see if credentials in here are also in the first arg TRUE if second arg is contained in first
References DBUS_PID_UNSET, DBUS_UID_UNSET, NULL.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_are_empty(DBusCredentials *credentials)
Checks whether a credentials object contains anything.
credentials the object TRUE if there are no credentials in the object
References DBUS_PID_UNSET, DBUS_UID_UNSET, NULL.
Referenced by _dbus_auth_get_identity.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_are_anonymous(DBusCredentials *credentials)
Checks whether a credentials object contains a user identity.
credentials the object TRUE if there are no user identities in the object
References DBUS_UID_UNSET, NULL.
Referenced by _dbus_keyring_new_for_credentials, _dbus_append_keyring_directory_for_credentials, _dbus_transport_get_is_anonymous.
dbus_bool_t _dbus_credentials_add_credentials(DBusCredentials *credentials, DBusCredentials *other_credentials)
Merge all credentials found in the second object into the first object, overwriting the first object if there are any overlaps.
credentials the object other_credentials credentials to merge FALSE if no memory
References _dbus_credentials_add_credential.
Referenced by _dbus_auth_set_credentials.
dbus_bool_t _dbus_credentials_add_credential(DBusCredentials *credentials, DBusCredentialType which, DBusCredentials *other_credentials)
Merge the given credential found in the second object into the first object, overwriting the first object's value for that credential.
Does nothing if the second object does not contain the specified credential. i.e., will never delete a credential from the first object. credentials the object which the credential to overwrite other_credentials credentials to merge FALSE if no memory
References DBUS_PID_UNSET, _dbus_credentials_add_pid, FALSE, DBUS_UID_UNSET, _dbus_credentials_add_unix_uid, NULL, _dbus_credentials_add_windows_sid, _dbus_credentials_add_linux_security_label, _dbus_credentials_add_adt_audit_data, TRUE.
Referenced by _dbus_credentials_add_credentials.
DBUS_PRIVATE_EXPORT void _dbus_credentials_clear(DBusCredentials *credentials)
Clear all credentials in the object.
credentials the object
References DBUS_PID_UNSET, DBUS_UID_UNSET, dbus_free, NULL.
Referenced by _dbus_auth_set_credentials.
DBUS_PRIVATE_EXPORT DBusCredentials* _dbus_credentials_copy(DBusCredentials *credentials)
Copy a credentials object.
credentials the object the copy or NULL
Referenced by _dbus_keyring_new_for_credentials.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_same_user(DBusCredentials *credentials, DBusCredentials *other_credentials)
Check whether the user-identifying credentials in two credentials objects are identical.
Credentials that are not related to the user are ignored, but any kind of user ID credentials must be the same (UNIX user ID, Windows user SID, etc.) and present in both objects for the function to return TRUE. credentials the object other_credentials credentials to compare TRUE if the two credentials refer to the same user
Referenced by _dbus_keyring_is_for_credentials.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_credentials_to_string_append(DBusCredentials *credentials, DBusString *string)
Convert the credentials in this object to a human-readable string format, and append to the given string.
credentials the object string append to this string FALSE if no memory
References FALSE, DBUS_UID_UNSET, _dbus_string_append_printf, DBUS_UID_FORMAT, TRUE, DBUS_PID_UNSET, DBUS_PID_FORMAT, NULL.