dbus-watch.h
_DBUS_WATCH_NVAL
DBusWatchList
Opaque data type representing a list of watches and a set of DBusAddWatchFunction/DBusRemoveWatchFunction.
Automatically handles removing/re-adding watches when the DBusAddWatchFunction is updated or changed. Holds a reference count to each watch.Used in the implementation of both DBusServer and DBusClient.
typedef dbus_bool_t(* DBusWatchHandler) (DBusWatch *watch, unsigned int flags, void *data))(DBusWatch *watch, unsigned int flags, void *data)
function to run when the watch is handled
DBUS_PRIVATE_EXPORT DBusWatch * _dbus_watch_new(DBusPollable fd, unsigned int flags, dbus_bool_t enabled, DBusWatchHandler handler, void *data, DBusFreeFunction free_data_function)
Creates a new DBusWatch.
Used to add a file descriptor to be polled by a main loop. fd the file descriptor to be watched. flags the conditions to watch for on the descriptor. enabled the initial enabled state handler the handler function data data for handler function free_data_function function to free the data the new DBusWatch object.
References _dbus_assert, DBusWatch::data, dbus_new0, DBusWatch::enabled, DBusWatch::fd, DBusWatch::flags, DBusWatch::free_data_function, DBusWatch::free_handler_data_function, DBusWatch::handler, DBusWatch::handler_data, NULL, DBusWatch::refcount.
Referenced by _dbus_server_new_for_socket, _dbus_transport_new_for_socket.
DBUS_PRIVATE_EXPORT DBusWatch * _dbus_watch_ref(DBusWatch *watch)
Increments the reference count of a DBusWatch object.
watch the watch object. the watch object.
References DBusWatch::refcount.
Referenced by _dbus_transport_handle_watch, _dbus_watch_list_add_watch.
DBUS_PRIVATE_EXPORT void _dbus_watch_unref(DBusWatch *watch)
Decrements the reference count of a DBusWatch object and finalizes the object if the count reaches zero.
watch the watch object.
References _dbus_assert, NULL, DBusWatch::refcount.
Referenced by _dbus_transport_handle_watch, _dbus_watch_list_free.
DBUS_PRIVATE_EXPORT void _dbus_watch_invalidate(DBusWatch *watch)
Clears the file descriptor from a now-invalid watch object so that no one tries to use it.
This is because a watch may stay alive due to reference counts after the file descriptor is closed. Invalidation makes it easier to catch bugs. It also keeps people from doing dorky things like assuming file descriptors are unique (never recycled). watch the watch object.
void _dbus_watch_sanitize_condition(DBusWatch *watch, unsigned int *condition)
Sanitizes the given condition so that it only contains flags that the DBusWatch requested.
e.g. if the watch is a DBUS_WATCH_READABLE watch then DBUS_WATCH_WRITABLE will be stripped from the condition. watch the watch object. condition address of the condition to sanitize.
References DBUS_WATCH_READABLE, DBUS_WATCH_WRITABLE, DBusWatch::flags.
Referenced by _dbus_transport_handle_watch.
void _dbus_watch_set_handler(DBusWatch *watch, DBusWatchHandler handler, void *data, DBusFreeFunction free_data_function)
Sets the handler for the watch.
Todothis function only exists because of the weird way connection watches are done, see the note in docs for _dbus_connection_handle_watch(). watch the watch handler the new handler data the data free_data_function free data with this
References DBusWatch::data, DBusWatch::free_data_function, DBusWatch::free_handler_data_function, DBusWatch::handler, DBusWatch::handler_data.
DBUS_PRIVATE_EXPORT DBusWatchList * _dbus_watch_list_new(void)
Creates a new watch list.
Returns NULL if insufficient memory exists.the new watch list, or NULL on failure.
References dbus_new0, NULL.
Referenced by _dbus_connection_new_for_transport.
DBUS_PRIVATE_EXPORT void _dbus_watch_list_free(DBusWatchList *watch_list)
Frees a DBusWatchList.
watch_list the watch list.
References _dbus_list_clear, _dbus_list_foreach, _dbus_watch_list_set_functions, _dbus_watch_unref, dbus_free, DBUS_WATCH_READABLE, DBUS_WATCH_WRITABLE, DBusWatch::flags, NULL, DBusWatchList::watches.
Referenced by _dbus_server_finalize_base.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_watch_list_set_functions(DBusWatchList *watch_list, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
Sets the watch functions.
This function is the "backend" for dbus_connection_set_watch_functions() and dbus_server_set_watch_functions(). watch_list the watch list. add_function the add watch function. remove_function the remove watch function. toggled_function function on toggling enabled flag, or NULL data the data for those functions. free_data_function the function to free the data. FALSE if not enough memory
References _dbus_list_get_first_link, _dbus_list_get_next_link, DBusList::data, NULL, DBusWatchList::watches.
Referenced by _dbus_babysitter_set_watch_functions, _dbus_watch_list_free, dbus_connection_set_watch_functions, dbus_server_set_watch_functions.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_watch_list_add_watch(DBusWatchList *watch_list, DBusWatch *watch)
Adds a new watch to the watch list, invoking the application DBusAddWatchFunction if appropriate.
watch_list the watch list. watch the watch to add. TRUE on success, FALSE if no memory.
References _dbus_list_append, _dbus_watch_ref, DBusWatchList::add_watch_function, FALSE, NULL, DBusWatchList::watches.
DBUS_PRIVATE_EXPORT void _dbus_watch_list_remove_watch(DBusWatchList *watch_list, DBusWatch *watch)
Removes a watch from the watch list, invoking the application's DBusRemoveWatchFunction if appropriate.
watch_list the watch list. watch the watch to remove.
References _dbus_assert_not_reached, _dbus_list_remove, NULL, DBusWatchList::remove_watch_function, DBusWatchList::watches.
void _dbus_watch_list_toggle_watch(DBusWatchList *watch_list, DBusWatch *watch, dbus_bool_t enabled)
Sets a watch to the given enabled state, invoking the application's DBusWatchToggledFunction if appropriate.
watch_list the watch list. watch the watch to toggle. enabled TRUE to enable
References DBusWatch::enabled, NULL, DBusWatchList::watch_toggled_function.
Referenced by _dbus_watch_list_toggle_all_watches.
void _dbus_watch_list_toggle_all_watches(DBusWatchList *watch_list, dbus_bool_t enabled)
Sets all watches to the given enabled state, invoking the application's DBusWatchToggledFunction if appropriate.
watch_list the watch list. enabled TRUE to enable
References _dbus_list_get_first_link, _dbus_list_get_next_link, _dbus_watch_list_toggle_watch, DBusList::data, NULL, DBusWatchList::watches.
Referenced by _dbus_server_toggle_all_watches.
dbus_bool_t _dbus_watch_get_enabled(DBusWatch *watch)
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_watch_get_oom_last_time(DBusWatch *watch)
DBUS_PRIVATE_EXPORT void _dbus_watch_set_oom_last_time(DBusWatch *watch, dbus_bool_t oom)
DBusSocket _dbus_watch_get_socket(DBusWatch *watch)
DBUS_PRIVATE_EXPORT DBusPollable _dbus_watch_get_pollable(DBusWatch *watch)