dbus-resources.c
DBusCounter* _dbus_counter_new(void)
Creates a new DBusCounter.
DBusCounter is used to count usage of some resource such as memory.new counter or NULL on failure
References _dbus_rmutex_new_at_location, dbus_free, dbus_new0, DBusCounter::mutex, NULL, DBusCounter::refcount.
Referenced by _dbus_transport_init_base.
DBusCounter* _dbus_counter_ref(DBusCounter *counter)
Increments refcount of the counter.
counter the counter the counter
References _dbus_assert, _dbus_rmutex_lock, _dbus_rmutex_unlock, DBusCounter::mutex, DBusCounter::refcount.
Referenced by _dbus_message_add_counter.
void _dbus_counter_unref(DBusCounter *counter)
Decrements refcount of the counter and possibly finalizes the counter.
counter the counter
References _dbus_assert, _dbus_rmutex_free_at_location, _dbus_rmutex_lock, _dbus_rmutex_unlock, dbus_free, FALSE, DBusCounter::mutex, DBusCounter::refcount.
Referenced by _dbus_message_remove_counter, _dbus_transport_finalize_base, _dbus_transport_init_base, dbus_connection_free_preallocated_send.
void _dbus_counter_adjust_size(DBusCounter *counter, long delta)
Adjusts the value of the size counter by the given delta which may be positive or negative.
This function may be called with locks held. After calling it, when any relevant locks are no longer held you must call _dbus_counter_notify(). counter the counter delta value to add to the size counter's current value
References _dbus_rmutex_lock, _dbus_rmutex_unlock, DBusCounter::mutex, DBusCounter::notify_function, DBusCounter::notify_pending, DBusCounter::notify_size_guard_value, NULL, DBusCounter::size_value, TRUE.
Referenced by _dbus_message_add_counter_link, _dbus_message_remove_counter.
void _dbus_counter_notify(DBusCounter *counter)
Calls the notify function from _dbus_counter_set_notify(), if that function has been specified and the counter has crossed the guard value (in either direction) since the last call to this function.
This function must not be called with locks held, since it can call out to user code.
References _dbus_rmutex_lock, _dbus_rmutex_unlock, FALSE, DBusCounter::mutex, DBusCounter::notify_data, DBusCounter::notify_function, DBusCounter::notify_pending, NULL.
Referenced by _dbus_message_remove_counter.
void _dbus_counter_adjust_unix_fd(DBusCounter *counter, long delta)
Adjusts the value of the unix fd counter by the given delta which may be positive or negative.
This function may be called with locks held. After calling it, when any relevant locks are no longer held you must call _dbus_counter_notify(). counter the counter delta value to add to the unix fds counter's current value
References _dbus_rmutex_lock, _dbus_rmutex_unlock, DBusCounter::mutex, DBusCounter::notify_function, DBusCounter::notify_pending, DBusCounter::notify_unix_fd_guard_value, NULL, TRUE, DBusCounter::unix_fd_value.
Referenced by _dbus_message_add_counter_link, _dbus_message_remove_counter.
long _dbus_counter_get_size_value(DBusCounter *counter)
Gets the current value of the size counter.
counter the counter its current size value
References DBusCounter::size_value.
Referenced by _dbus_transport_get_dispatch_status, _dbus_transport_set_pending_fds_function, dbus_connection_get_outgoing_size.
long _dbus_counter_get_unix_fd_value(DBusCounter *counter)
Gets the current value of the unix fd counter.
counter the counter its current unix fd value
References DBusCounter::unix_fd_value.
Referenced by _dbus_transport_get_dispatch_status, _dbus_transport_set_pending_fds_function, dbus_connection_get_outgoing_size, dbus_connection_get_outgoing_unix_fds.
void _dbus_counter_set_notify(DBusCounter *counter, long size_guard_value, long unix_fd_guard_value, DBusCounterNotifyFunction function, void *user_data)
Sets the notify function for this counter; the notify function is called whenever the counter's values cross the guard values in either direction (moving up, or moving down).
counter the counter size_guard_value the value we're notified if the size counter crosses unix_fd_guard_value the value we're notified if the unix fd counter crosses function function to call in order to notify user_data data to pass to the function
References _dbus_rmutex_lock, _dbus_rmutex_unlock, FALSE, DBusCounter::mutex, DBusCounter::notify_data, DBusCounter::notify_function, DBusCounter::notify_pending, DBusCounter::notify_size_guard_value, DBusCounter::notify_unix_fd_guard_value.
Referenced by _dbus_transport_finalize_base, _dbus_transport_init_base, _dbus_transport_set_max_received_size, _dbus_transport_set_max_received_unix_fds.