DBusSysdeps
DBusSystemLogSeverity
typedef unsigned long dbus_pid_t
A process ID.
typedef unsigned long dbus_uid_t
A user ID.
typedef unsigned long dbus_gid_t
A group ID.
typedef struct DBusAtomic DBusAtomic
Opaque type representing an atomically-modifiable integer that can be used from multiple threads.
typedef int DBusPollable
typedef struct DBusDirIter DBusDirIter
Opaque type for reading a directory listing.
typedef void(* DBusSignalHandler) (int sig))(int sig)
A UNIX signal handler.
typedef union DBusGUID DBusGUID
Type representing a universally unique ID.
Todorename to UUID instead of GUID
typedef struct DBusRLimit DBusRLimit
void _dbus_abort(void)
Aborts the program with SIGABRT (dumping core).
References _dbus_print_backtrace, _dbus_getenv, _dbus_pid_for_log, _dbus_sleep_milliseconds, _dbus_exit.
Referenced by _dbus_real_assert, _dbus_real_assert_not_reached, dbus_malloc, dbus_malloc0, dbus_realloc, _dbus_write_socket_two, _dbus_get_tmpdir.
DBUS_PRIVATE_EXPORT const char * _dbus_getenv(const char *varname)
Wrapper for getenv().
varname name of environment variable value of environment variable or NULL if unset
References _dbus_check_setuid, NULL.
Referenced by _dbus_abort, _dbus_append_keyring_directory_for_credentials, _dbus_become_daemon, _dbus_get_autolaunch_address, _dbus_get_standard_session_servicedirs, _dbus_real_assert_not_reached, _dbus_server_listen_platform_specific, _dbus_server_new_for_launchd.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_clearenv(void)
Wrapper for clearenv().
TRUE on success.
References FALSE, NULL, TRUE.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_split_paths_and_append(DBusString *dirs, const char *suffix, DBusList **dir_list)
Split paths into a list of char strings.
dirs string with pathes suffix string concated to each path in dirs dir_list contains a list of splitted pathes return TRUE is pathes could be splittes,FALSE in oom case
References _dbus_concat_dir_and_file, _dbus_list_append, _dbus_list_clear, _dbus_list_foreach, _dbus_string_chop_white, _dbus_string_copy_data, _dbus_string_copy_len, _dbus_string_find, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, dbus_free, FALSE, NULL, TRUE.
Referenced by _dbus_get_standard_session_servicedirs, _dbus_get_standard_system_servicedirs.
dbus_bool_t _dbus_check_setuid(void)
NOTE: If you modify this function, please also consider making the corresponding change in GLib.
See glib/gutils.c:g_check_setuid().Returns TRUE if the current process was executed as setuid (or an equivalent __libc_enable_secure is available). See: http://osdir.com/ml/linux.lfs.hardened/2007-04/msg00032.html
References FALSE, TRUE.
Referenced by _dbus_get_autolaunch_address, _dbus_getenv, _dbus_keyring_new_for_credentials, _dbus_lookup_launchd_socket, _dbus_threads_init_platform_specific.
char** _dbus_get_environment(void)
Gets a NULL-terminated list of key=value pairs from the environment.
Use dbus_free_string_array to free it.the environment or NULL on OOM
References _dbus_assert, _dbus_assert_not_reached, _dbus_path_is_absolute, _dbus_strdup, _dbus_string_equal_c_str, _dbus_string_free, _dbus_string_get_dirname, _dbus_string_init, _dbus_string_init_const, _dbus_warn, dbus_free_string_array, dbus_new0, FALSE, NULL, TRUE.
static int _dbus_socket_printable(DBusSocket s)
static dbus_bool_t _dbus_socket_is_valid(DBusSocket s)
static void _dbus_socket_invalidate(DBusSocket *s)
static int _dbus_socket_get_int(DBusSocket s)
static DBusSocket _dbus_socket_get_invalid(void)
dbus_bool_t _dbus_set_socket_nonblocking(DBusSocket fd, DBusError *error)
Sets a file descriptor to be nonblocking.
fd the file descriptor. error address of error location. TRUE on success. handle the file descriptor. error address of error location. TRUE on success.
References _dbus_error_from_errno, _dbus_strerror_from_errno, dbus_set_error, FALSE, TRUE.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_close_socket(DBusSocket fd, DBusError *error)
Closes a socket.
Should not be used on non-socket file descriptors or handles. fd the socket error return location for an error FALSE if error is set Closes a socket. fd the file descriptor error error object FALSE if error set
References _dbus_close, _dbus_error_from_errno, _dbus_strerror_from_errno, dbus_set_error, FALSE, TRUE.
Referenced by _dbus_server_listen_platform_specific, _dbus_server_new_for_domain_socket, _dbus_server_new_for_tcp_socket.
DBUS_PRIVATE_EXPORT int _dbus_read_socket(DBusSocket fd, DBusString *buffer, int count)
Like _dbus_read(), but only works on sockets so is available on Windows.
fd the socket buffer string to append data to count max amount of data to read number of bytes appended to the string Like _dbus_read(), but only works on sockets so is available on Windows.Thin wrapper around the read() system call that appends the data it reads to the DBusString buffer. It appends up to the given count, and returns the same value and same errno as read(). The only exception is that _dbus_read_socket() handles EINTR for you. _dbus_read_socket() can return ENOMEM, even though regular UNIX read doesn't. fd the file descriptor to read from buffer the buffer to append data to count the amount of data to read the number of bytes read or -1
References _dbus_assert, _dbus_read, _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_set_length, _dbus_verbose_bytes_of_string.
Referenced by _dbus_read_credentials_socket, _dbus_read_socket_with_unix_fds.
DBUS_PRIVATE_EXPORT int _dbus_write_socket(DBusSocket fd, const DBusString *buffer, int start, int len)
Like _dbus_write(), but only supports sockets and is thus available on Windows.
fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error Like _dbus_write(), but only supports sockets and is thus available on Windows. fd the file descriptor to write buffer the buffer to write data from start the first byte in the buffer to write len the number of bytes to try to write the number of bytes written or -1 on error
References _dbus_strerror_from_errno, _dbus_verbose_bytes_of_string, _dbus_write.
Referenced by _dbus_send_credentials_socket.
int _dbus_write_socket_two(DBusSocket fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2)
Like _dbus_write_two() but only works on sockets and is thus available on Windows.
fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error Like _dbus_write_two() but only works on sockets and is thus available on Windows.The return value is the number of bytes written in the first buffer, plus the number written in the second. If the first buffer is written successfully and an error occurs writing the second, the number of bytes in the first is returned (i.e. the error is ignored), on systems that don't have writev. Handles EINTR for you. The second buffer may be NULL. fd the file descriptor buffer1 first buffer start1 first byte to write in first buffer len1 number of bytes to write from first buffer buffer2 second buffer, or NULL start2 first byte to write in second buffer len2 number of bytes to write in second buffer total bytes written from both buffers, or -1 on error
References _dbus_abort, _dbus_assert, _dbus_assert_not_reached, _DBUS_LOCK, _dbus_strerror_from_errno, _DBUS_UNLOCK, _dbus_write_two, _DBUS_ZERO, FALSE, NULL, TRUE.
int _dbus_read_socket_with_unix_fds(DBusSocket fd, DBusString *buffer, int count, int *fds, int *n_fds)
Like _dbus_read_socket() but also tries to read unix fds from the socket.
When there are more fds to read than space in the array passed this function will fail with ENOSPC. fd the socket buffer string to append data to count max amount of data to read fds array to place read file descriptors in n_fds on input space in fds array, on output how many fds actually got read number of bytes appended to string
References _dbus_assert, _dbus_read_socket, _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_set_length, _DBUS_ZERO, FALSE.
DBUS_PRIVATE_EXPORT int _dbus_write_socket_with_unix_fds(DBusSocket fd, const DBusString *buffer, int start, int len, const int *fds, int n_fds)
int _dbus_write_socket_with_unix_fds_two(DBusSocket fd, const DBusString *buffer1, int start1, int len1, const DBusString *buffer2, int start2, int len2, const int *fds, int n_fds)
DBusSocket _dbus_connect_tcp_socket(const char *host, const char *port, const char *family, DBusError *error)
Creates a socket and connects to a socket at the given host and port.
The connection fd is returned, and is set up as nonblocking.This will set FD_CLOEXEC for the socket returned host the host name to connect to port the port to connect to family the address family to listen on, NULL for all error return location for error code connection file descriptor or -1 on error The connection fd is returned, and is set up as nonblocking. host the host name to connect to port the port to connect to family the address family to listen on, NULL for all error return location for error code connection file descriptor or -1 on error
DBusSocket _dbus_connect_tcp_socket_with_nonce(const char *host, const char *port, const char *family, const char *noncefile, DBusError *error)
int _dbus_listen_tcp_socket(const char *host, const char *port, const char *family, DBusString *retport, DBusSocket **fds_p, DBusError *error)
Creates a socket and binds it to the given path, then listens on the socket.
The socket is set to be nonblocking. In case of port=0 a random free port is used and returned in the port parameter. If inaddr_any is specified, the hostname is ignored.This will set FD_CLOEXEC for the socket returned host the host name to listen on port the port to listen on, if zero a free port will be used family the address family to listen on, NULL for all retport string to return the actual port listened on fds_p location to store returned file descriptors error return location for errors the number of listening file descriptors or -1 on error The socket is set to be nonblocking. In case of port=0 a random free port is used and returned in the port parameter. If inaddr_any is specified, the hostname is ignored. host the host name to listen on port the port to listen on, if zero a free port will be used family the address family to listen on, NULL for all retport string to return the actual port listened on fds_p location to store returned file descriptors error return location for errors the number of listening file descriptors or -1 on error
References _dbus_assert, _dbus_assert_not_reached, _dbus_close, _dbus_credentials_add_linux_security_label, _dbus_error_from_errno, _dbus_string_append, _dbus_string_free, _dbus_string_init_preallocated, _dbus_string_set_length, _dbus_warn, _DBUS_ZERO, DBUS_ERROR_BAD_ADDRESS, DBUS_ERROR_INVALID_ARGS, DBUS_ERROR_IO_ERROR, DBUS_ERROR_NO_MEMORY, dbus_free, dbus_realloc, dbus_set_error, FALSE, NULL, TRUE.
Referenced by _dbus_server_new_for_tcp_socket.
DBusSocket _dbus_accept(DBusSocket listen_fd)
Accepts a connection on a listening socket.
Handles EINTR for you.This will enable FD_CLOEXEC for the returned socket. listen_fd the listen file descriptor the connection fd of the client, or -1 on error Handles EINTR for you. listen_fd the listen file descriptor the connection fd of the client, or -1 on error
References _dbus_fd_set_close_on_exec, NULL.
dbus_bool_t _dbus_read_credentials_socket(DBusSocket client_fd, DBusCredentials *credentials, DBusError *error)
Reads a single byte which must be nul (an error occurs otherwise), and reads unix credentials if available.
Clears the credentials object, then adds pid/uid if available, so any previous credentials stored in the object are lost.DBusServer makes the security assumption that the credentials returned by this method are the credentials that were active at the time the socket was opened. Do not add APIs to this method that would break that assumption.In particular, it is incorrect to use any API of the form "get the process ID at the other end of the connection, then determine its uid, gid, or other credentials from the pid" (e.g. looking in /proc on Linux). If we did that, we would be vulnerable to several attacks. A malicious process could queue up the rest of the authentication handshake and a malicious message that it should not be allowed to send, then race with the DBusServer to exec() a more privileged (e.g. setuid) binary that would have been allowed to send that message; or it could exit, and arrange for enough setuid processes to be started that its pid would be recycled for one of those processes with high probability; or it could fd-pass the connection to a more privileged process.Return value indicates whether a byte was read, not whether we got valid credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte is available, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. client_fd the client file descriptor credentials object to add client credentials to error location to store error code TRUE on success Fills in pid/uid/gid with -1 if no credentials are available. Return value indicates whether a byte was read, not whether we got valid credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte is available, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. handle the client file descriptor credentials struct to fill with credentials of client error location to store error code TRUE on success
References _dbus_credentials_add_pid, _dbus_credentials_add_windows_sid, _dbus_read_socket, _dbus_string_free, _dbus_string_init, FALSE, NULL, TRUE.
dbus_bool_t _dbus_send_credentials_socket(DBusSocket server_fd, DBusError *error)
Sends a single nul byte with our UNIX credentials as ancillary data.
Returns TRUE if the data was successfully written. On systems that don't support sending credentials, just writes a byte, doesn't send any credentials. On some systems, such as Linux, reading/writing the byte isn't actually required, but we do it anyway just to avoid multiple codepaths.Fails if no byte can be written, so you must select() first.The point of the byte is that on some systems we have to use sendmsg()/recvmsg() to transmit credentials. server_fd file descriptor for connection to server error return location for error code TRUE if the byte was sent
References _dbus_assert, _dbus_error_from_errno, _dbus_strerror_from_errno, _dbus_string_init_const_len, _dbus_write_socket, DBUS_ERROR_IO_ERROR, dbus_set_error, FALSE, TRUE.
dbus_bool_t _dbus_credentials_add_from_user(DBusCredentials *credentials, const DBusString *username)
Adds the credentials corresponding to the given username.
credentials credentials to fill in username the username TRUE if the username existed and we got some credentials Used among other purposes to parses a desired identity provided from a client in the auth protocol. On UNIX this means parsing a UID, on Windows probably parsing an SID string.Todothis is broken because it treats OOM and parse error the same way. Needs a DBusError. credentials credentials to fill in username the username TRUE if the username existed and we got some credentials
References _dbus_credentials_add_unix_uid, _dbus_credentials_add_windows_sid, _dbus_user_database_get_system, _dbus_user_database_get_username, _dbus_user_database_lock_system, _dbus_user_database_unlock_system, FALSE, NULL, TRUE, DBusUserInfo::uid.
dbus_bool_t _dbus_credentials_add_from_current_process(DBusCredentials *credentials)
Adds the credentials of the current process to the passed-in credentials object.
credentials credentials to add to FALSE if no memory; does not properly roll back on failure, so only some credentials may have been added
References _dbus_credentials_add_pid, _dbus_credentials_add_windows_sid, _dbus_getpid, FALSE, NULL, TRUE.
Referenced by _dbus_credentials_new_from_current_process, _dbus_keyring_new_for_credentials.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_append_user_from_current_process(DBusString *str)
Append to the string the identity we would like to have when we authenticate, on UNIX this is the current process UID and on Windows something else, probably a Windows SID string.
No escaping is required, that is done in dbus-auth.c. The username here need not be anything human-readable, it can be the machine-readable form i.e. a user id. str the string to append to FALSE on no memory No escaping is required, that is done in dbus-auth.c. The username here need not be anything human-readable, it can be the machine-readable form i.e. a user id. str the string to append to FALSE on no memory Todoto which class belongs this
References _dbus_geteuid, _dbus_getpid, _dbus_string_append, _dbus_string_append_uint, FALSE, NULL.
Referenced by _dbus_read_local_machine_uuid.
dbus_bool_t _dbus_parse_unix_user_from_config(const DBusString *username, dbus_uid_t *uid_p)
Parse a UNIX user from the bus config file.
On Windows, this should simply always fail (just return FALSE). username the username text uid_p place to return the uid TRUE on success
References _dbus_get_user_id, FALSE.
dbus_bool_t _dbus_parse_unix_group_from_config(const DBusString *groupname, dbus_gid_t *gid_p)
Parse a UNIX group from the bus config file.
On Windows, this should simply always fail (just return FALSE). groupname the groupname text gid_p place to return the gid TRUE on success
References _dbus_get_group_id, FALSE.
dbus_bool_t _dbus_unix_groups_from_uid(dbus_uid_t uid, dbus_gid_t **group_ids, int *n_group_ids)
Gets all groups corresponding to the given UNIX user ID.
On UNIX, just calls _dbus_groups_from_uid(). On Windows, should always fail since we don't know any UNIX groups. uid the UID group_ids return location for array of group IDs n_group_ids return location for length of returned array TRUE if the UID existed and we got some credentials
References _dbus_groups_from_uid, FALSE, NULL.
dbus_bool_t _dbus_unix_user_is_at_console(dbus_uid_t uid, DBusError *error)
Checks to see if the UNIX user ID is at the console.
Should always fail on Windows (set the error to DBUS_ERROR_NOT_SUPPORTED). uid UID of person to check error return location for errors TRUE if the UID is the same as the console user and there are no errors
References _dbus_is_console_user, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, FALSE.
dbus_bool_t _dbus_unix_user_is_process_owner(dbus_uid_t uid)
Checks to see if the UNIX user ID matches the UID of the process.
Should always return FALSE on Windows. uid the UNIX user ID TRUE if this uid owns the process.
References _dbus_geteuid, FALSE.
dbus_bool_t _dbus_windows_user_is_process_owner(const char *windows_sid)
Checks to see if the Windows user SID matches the owner of the process.
Should always return FALSE on UNIX. windows_sid the Windows user SID TRUE if this user owns the process.
References FALSE, TRUE.
dbus_bool_t _dbus_append_keyring_directory_for_credentials(DBusString *directory, DBusCredentials *credentials)
Appends the directory in which a keyring for the given credentials should be stored.
The credentials should have either a Windows or UNIX user in them. The directory should be an absolute path.On UNIX the directory is ~/.dbus-keyrings while on Windows it should probably be something else, since the dotfile convention is not normal on Windows. directory string to append directory to credentials credentials the directory should be for FALSE on no memory
References _dbus_assert, _dbus_concat_dir_and_file, _dbus_credentials_are_anonymous, _dbus_credentials_get_unix_uid, _dbus_getenv, _dbus_homedir_from_uid, _dbus_string_append, _dbus_string_copy, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, _dbus_string_set_length, _dbus_warn, DBUS_UID_UNSET, FALSE, NULL, TRUE.
Referenced by _dbus_keyring_new_for_credentials.
dbus_bool_t _dbus_daemon_is_session_bus_address_published(const char *scope)
dbus_bool_t _dbus_daemon_publish_session_bus_address(const char *address, const char *shm_name)
void _dbus_daemon_unpublish_session_bus_address(void)
dbus_bool_t _dbus_socket_can_pass_unix_fd(DBusSocket fd)
Checks whether file descriptors may be passed via the socket.
fd the socket TRUE when fd passing over this socket is supported
References _DBUS_ZERO, FALSE.
DBUS_PRIVATE_EXPORT dbus_int32_t _dbus_atomic_inc(DBusAtomic *atomic)
Atomically increments an integer.
atomic pointer to the integer to increment the value before incrementing
References DBusAtomic::value.
Referenced by _dbus_babysitter_ref, _dbus_connection_ref_unlocked, _dbus_pending_call_ref_unlocked, _dbus_server_init_base, _dbus_server_ref_unlocked, dbus_connection_add_filter, dbus_connection_ref, dbus_malloc, dbus_malloc0, dbus_message_copy, dbus_message_ref, dbus_pending_call_ref, dbus_realloc, dbus_server_ref, dbus_server_unref.
DBUS_PRIVATE_EXPORT dbus_int32_t _dbus_atomic_dec(DBusAtomic *atomic)
Atomically decrement an integer.
atomic pointer to the integer to decrement the value before decrementing
References DBusAtomic::value.
Referenced by _dbus_babysitter_unref, _dbus_connection_unref_unlocked, _dbus_pending_call_unref_and_unlock, _dbus_server_unref_unlocked, dbus_connection_unref, dbus_free, dbus_message_unref, dbus_pending_call_unref, dbus_server_ref, dbus_server_unref.
DBUS_PRIVATE_EXPORT dbus_int32_t _dbus_atomic_get(DBusAtomic *atomic)
Atomically get the value of an integer.
It may change at any time thereafter, so this is mostly only useful for assertions. atomic pointer to the integer to get the value at this moment
References DBusAtomic::value.
Referenced by _dbus_connection_close_if_only_one_ref.
static DBusPollable _dbus_socket_get_pollable(DBusSocket s)
static int _dbus_pollable_printable(DBusPollable p)
static dbus_bool_t _dbus_pollable_is_valid(DBusPollable p)
static void _dbus_pollable_invalidate(DBusPollable *p)
static dbus_bool_t _dbus_pollable_equals(DBusPollable a, DBusPollable b)
DBUS_PRIVATE_EXPORT int _dbus_poll(DBusPollFD *fds, int n_fds, int timeout_milliseconds)
Wrapper for poll().
fds the file descriptors to poll n_fds number of descriptors in the array timeout_milliseconds timeout or -1 for infinite numbers of fds with revents, or <0 on error
References _dbus_assert_not_reached, _DBUS_POLLERR, _DBUS_POLLIN, _DBUS_POLLOUT, _dbus_strerror_from_errno, DBusPollFD::events, FALSE, DBusPollFD::fd, NULL, DBusPollFD::revents.
DBUS_PRIVATE_EXPORT void _dbus_sleep_milliseconds(int milliseconds)
Sleeps the given number of milliseconds.
milliseconds number of milliseconds
Referenced by _dbus_abort.
DBUS_PRIVATE_EXPORT void _dbus_get_monotonic_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Use the monotonic clock if available, to avoid problems when the system time changes. tv_sec return location for number of seconds tv_usec return location for number of microseconds
References _dbus_get_real_time, NULL.
DBUS_PRIVATE_EXPORT void _dbus_get_real_time(long *tv_sec, long *tv_usec)
Get current time, as in gettimeofday().
Never uses the monotonic clock. tv_sec return location for number of seconds tv_usec return location for number of microseconds
References DBUS_INT64_CONSTANT, dbus_uint64_t, NULL.
Referenced by _dbus_generate_uuid, _dbus_get_monotonic_time.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_create_directory(const DBusString *filename, DBusError *error)
directory interface
directory interface filename directory filename error initialized error object TRUE on success
References _dbus_strerror_from_errno, DBUS_ERROR_FAILED, dbus_set_error, FALSE, NULL, TRUE.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_delete_directory(const DBusString *filename, DBusError *error)
Removes a directory; Directory must be empty.
filename directory filename error initialized error object TRUE on success
References DBUS_ERROR_FAILED, dbus_set_error, FALSE, TRUE.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_concat_dir_and_file(DBusString *dir, const DBusString *next_component)
Appends the given filename to the given directory.
Todoit might be cute to collapse multiple '/' such as "foo//" concat "//bar" dir the directory name next_component the filename TRUE on success Todoit might be cute to collapse multiple '/' such as "foo//" concat "//bar" dir the directory name next_component the filename TRUE on success
References _dbus_string_append_byte, _dbus_string_copy, _dbus_string_shorten, FALSE, TRUE.
Referenced by _dbus_append_keyring_directory_for_credentials, _dbus_get_standard_session_servicedirs, _dbus_get_standard_system_servicedirs, _dbus_server_listen_platform_specific, _dbus_sha_compute, _dbus_split_paths_and_append, _dbus_user_at_console.
dbus_bool_t _dbus_string_get_dirname(const DBusString *filename, DBusString *dirname)
Get the directory name from a complete filename.
filename the filename dirname string to append directory name to FALSE if no memory
References _dbus_assert, _dbus_string_append, _dbus_string_copy_len, _dbus_string_find_byte_backward, NULL.
Referenced by _dbus_directory_close, _dbus_get_environment.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_path_is_absolute(const DBusString *filename)
Checks whether the filename is an absolute path.
filename the filename TRUE if an absolute path
References FALSE.
Referenced by _dbus_get_environment, _dbus_get_standard_session_servicedirs.
dbus_bool_t _dbus_get_standard_session_servicedirs(DBusList **dirs)
Returns the standard directories for a session bus to look for service activation files.
On UNIX this should be the standard xdg freedesktop.org data directories:XDG_DATA_HOME=${XDG_DATA_HOME-$HOME/.local/share} XDG_DATA_DIRS=${XDG_DATA_DIRS-/usr/local/share:/usr/share}andDBUS_DATADIR dirs the directory list we are returning FALSE on OOM On Windows this should be data directories:CommonProgramFiles%/dbusandrelocated DBUS_DATADIR dirs the directory list we are returning FALSE on OOM
References _dbus_concat_dir_and_file, _dbus_getenv, _dbus_homedir_from_current_process, _dbus_path_is_absolute, _dbus_split_paths_and_append, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, FALSE, NULL, TRUE.
dbus_bool_t _dbus_get_standard_system_servicedirs(DBusList **dirs)
Returns the standard directories for a system bus to look for service activation files.
On UNIX this should be the standard xdg freedesktop.org data directories:XDG_DATA_DIRS=${XDG_DATA_DIRS-/usr/local/share:/usr/share}andDBUS_DATADIROn Windows there is no system bus and this function can return nothing. dirs the directory list we are returning FALSE on OOM
References _dbus_concat_dir_and_file, _dbus_split_paths_and_append, _dbus_string_append, _dbus_string_init_const, FALSE, NULL, TRUE.
dbus_bool_t _dbus_append_system_config_file(DBusString *str)
Append the absolute path of the system.conf file (there is no system bus on Windows so this can just return FALSE and print a warning or something)
str the string to append to FALSE if no memory
References _dbus_string_append.
dbus_bool_t _dbus_append_session_config_file(DBusString *str)
Append the absolute path of the session.conf file.
str the string to append to FALSE if no memory
References _dbus_string_append.
DBusDirIter* _dbus_directory_open(const DBusString *filename, DBusError *error)
Open a directory to iterate over.
filename the directory name error exception return object or NULL new iterator, or NULL on error
References _dbus_error_from_errno, _dbus_string_append, _dbus_string_ends_with_c_str, _dbus_string_free, _dbus_string_init_from_string, DBusDirIter::d, DBUS_ERROR_NO_MEMORY, dbus_free, dbus_new0, dbus_set_error, FALSE, NULL, TRUE.
dbus_bool_t _dbus_directory_get_next_file(DBusDirIter *iter, DBusString *filename, DBusError *error)
Get next file in the directory.
Will not return "." or ".." on UNIX. If an error occurs, the contents of "filename" are undefined. The error is never set if the function succeeds.This function is not re-entrant, and not necessarily thread-safe. Only use it for test code or single-threaded utilities. iter the iterator filename string to be set to the next file in the dir error return location for error TRUE if filename was filled in with a new filename Will not return "." or ".." on UNIX. If an error occurs, the contents of "filename" are undefined. The error is never set if the function succeeds. iter the iterator filename string to be set to the next file in the dir error return location for error TRUE if filename was filled in with a new filename
References _dbus_error_from_errno, _dbus_string_append, _dbus_string_set_length, DBusDirIter::d, DBUS_ERROR_NO_MEMORY, dbus_set_error, FALSE, TRUE.
void _dbus_directory_close(DBusDirIter *iter)
Closes a directory iteration.
References DBusDirIter::d, dbus_free, _dbus_string_get_dirname, _dbus_assert, NULL, _dbus_string_append, _dbus_string_copy_len, _dbus_string_find_byte_backward.
dbus_bool_t _dbus_check_dir_is_private_to_user(DBusString *dir, DBusError *error)
Checks to make sure the given directory is private to the user.
dir the name of the directory error error return FALSE on failure
References _dbus_assert, _dbus_error_from_errno, _dbus_strdup, _dbus_warn, DBUS_ERROR_FAILED, DBUS_ERROR_NO_MEMORY, dbus_free, DBUS_GID_FORMAT, DBUS_GID_UNSET, dbus_malloc, dbus_new, dbus_realloc, dbus_set_error, DBUS_UID_UNSET, FALSE, DBusUserInfo::group_ids, DBusUserInfo::homedir, DBusUserInfo::n_group_ids, NULL, DBusUserInfo::primary_gid, TRUE, DBusUserInfo::uid, DBusUserInfo::username.
DBUS_PRIVATE_EXPORT const char* _dbus_get_tmpdir(void)
Gets the temporary files directory by inspecting the environment variables TMPDIR, TMP, and TEMP in that order.
If none of those are set "/tmp" is returnedlocation of temp directory, or NULL if no memory for locking
References _dbus_abort, _dbus_assert, _dbus_close_all, _dbus_error_from_errno, _DBUS_LOCK, _dbus_read, _dbus_string_init, _dbus_string_set_length, _DBUS_UNLOCK, _dbus_warn, DBUS_ERROR_SPAWN_EXEC_FAILED, dbus_set_error, FALSE, NULL, READ_END, TRUE, WRITE_END.
_DBUS_GNUC_WARN_UNUSED_RESULT dbus_bool_t _dbus_generate_random_bytes_buffer(char *buffer, int n_bytes, DBusError *error)
Random numbers.
Random numbers. buffer an allocated buffer n_bytes the number of bytes in buffer to write to error location to store reason for failure TRUE on success
References _dbus_generate_random_bytes, _dbus_string_copy_to_buffer, _dbus_string_free, _dbus_string_init, FALSE, TRUE.
Referenced by _dbus_generate_uuid.
dbus_bool_t _dbus_generate_random_bytes(DBusString *str, int n_bytes, DBusError *error)
Generates the given number of securely random bytes, using the best mechanism we can come up with.
str the string n_bytes the number of random bytes to append to string error location to store reason for failure TRUE on success, FALSE on error Generates the given number of securely random bytes, using the best mechanism we can come up with. str the string n_bytes the number of random bytes to append to string error location to store reason for failure TRUE on success
References _dbus_close, _dbus_error_from_errno, _dbus_read, _dbus_string_get_data_len, _dbus_string_lengthen, _dbus_string_set_length, DBUS_ERROR_IO_ERROR, dbus_set_error, FALSE, NULL, TRUE.
Referenced by _dbus_generate_random_ascii, _dbus_generate_random_bytes_buffer.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_generate_random_ascii(DBusString *str, int n_bytes, DBusError *error)
Generates the given number of random bytes, where the bytes are chosen from the alphanumeric ASCII subset.
str the string n_bytes the number of random ASCII bytes to append to string error location to store reason for failure TRUE on success, FALSE if no memory or other failure
References _dbus_assert, _dbus_generate_random_bytes, _dbus_string_validate_ascii, FALSE, TRUE.
Referenced by _dbus_server_listen_platform_specific, _dbus_string_save_to_file.
DBUS_PRIVATE_EXPORT const char* _dbus_error_from_errno(int error_number)
Converts a UNIX errno, or Windows errno or WinSock error value into a DBusError name.
Todoshould cover more errnos, specifically those from open(). error_number the errno. an error name
References DBUS_ERROR_ACCESS_DENIED, DBUS_ERROR_ADDRESS_IN_USE, DBUS_ERROR_FAILED, DBUS_ERROR_FILE_EXISTS, DBUS_ERROR_FILE_NOT_FOUND, DBUS_ERROR_LIMITS_EXCEEDED, DBUS_ERROR_NO_MEMORY, DBUS_ERROR_NO_NETWORK, DBUS_ERROR_NO_SERVER, DBUS_ERROR_NOT_SUPPORTED, DBUS_ERROR_TIMEOUT.
Referenced by _dbus_append_address_from_socket, _dbus_become_daemon, _dbus_change_to_daemon_user, _dbus_check_dir_is_private_to_user, _dbus_close, _dbus_close_socket, _dbus_command_for_pid, _dbus_connect_exec, _dbus_connect_unix_socket, _dbus_directory_get_next_file, _dbus_directory_open, _dbus_dup, _dbus_error_from_system_errno, _dbus_file_get_contents, _dbus_generate_random_bytes, _dbus_get_tmpdir, _dbus_is_console_user, _dbus_listen_systemd_sockets, _dbus_listen_tcp_socket, _dbus_listen_unix_socket, _dbus_send_credentials_socket, _dbus_set_socket_nonblocking, _dbus_socketpair, _dbus_stat, _dbus_string_save_to_file.
DBUS_PRIVATE_EXPORT const char* _dbus_error_from_system_errno(void)
Converts the current system errno value into a DBusError name.
an error name
References _dbus_error_from_errno.
int _dbus_save_socket_errno(void)
void _dbus_restore_socket_errno(int saved_errno)
void _dbus_set_errno_to_zero(void)
Assign 0 to the global errno variable.
Referenced by _dbus_string_parse_int, _dbus_string_parse_uint.
dbus_bool_t _dbus_get_is_errno_eagain_or_ewouldblock(int e)
See if errno is EAGAIN or EWOULDBLOCK (this has to be done differently for Winsock so is abstracted)
TRUE if e == EAGAIN or e == EWOULDBLOCK
References FALSE, NULL, TRUE.
dbus_bool_t _dbus_get_is_errno_enomem(int e)
See if errno is ENOMEM.
TRUE if e == ENOMEM
dbus_bool_t _dbus_get_is_errno_eintr(int e)
See if errno is EINTR.
TRUE if e == EINTR
dbus_bool_t _dbus_get_is_errno_epipe(int e)
See if errno is EPIPE.
TRUE if errno == EPIPE
dbus_bool_t _dbus_get_is_errno_etoomanyrefs(int e)
See if errno is ETOOMANYREFS.
TRUE if errno == ETOOMANYREFS
References FALSE.
DBUS_PRIVATE_EXPORT const char* _dbus_strerror_from_errno(void)
Get error message from errno.
_dbus_strerror(errno)
Referenced by _dbus_close_socket, _dbus_create_directory, _dbus_delete_file, _dbus_poll, _dbus_send_credentials_socket, _dbus_set_socket_nonblocking, _dbus_socketpair, _dbus_write_socket, _dbus_write_socket_two.
void _dbus_disable_sigpipe(void)
signal (SIGPIPE, SIG_IGN);
DBUS_PRIVATE_EXPORT void _dbus_exit(int code) _DBUS_GNUC_NORETURN
Exit the process, returning the given value.
code the exit code
References NULL.
Referenced by _dbus_abort.
DBUS_PRIVATE_EXPORT int _dbus_printf_string_upper_bound(const char *format, va_list args)
Measure the length of the given format string and arguments, not including the terminating nul.
format a printf-style format string args arguments for the format string length of the given format string and args, or -1 if no memory Measure the length of the given format string and arguments, not including the terminating nul.
dbus_bool_t _dbus_stat(const DBusString *filename, DBusStat *statbuf, DBusError *error)
stat() wrapper.
filename the filename to stat statbuf the stat info to fill in error return location for error FALSE if error was set
References _dbus_error_from_errno, DBusStat::atime, DBusStat::ctime, DBUS_GID_UNSET, DBUS_INT64_CONSTANT, dbus_int64_t, dbus_set_error, DBUS_UID_UNSET, FALSE, DBusStat::gid, DBusStat::mode, DBusStat::mtime, DBusStat::nlink, NULL, DBusStat::size, TRUE, DBusStat::uid.
Referenced by _dbus_is_console_user.
DBUS_PRIVATE_EXPORT dbus_bool_t _dbus_socketpair(DBusSocket *fd1, DBusSocket *fd2, dbus_bool_t blocking, DBusError *error)
Creates pair of connect sockets (as in socketpair()).
Sets both ends of the pair nonblocking.Marks both file descriptors as close-on-exec fd1 return location for one end fd2 return location for the other end blocking TRUE if pair should be blocking error error return FALSE on failure (if error is set)
References _dbus_close, _dbus_error_from_errno, _dbus_fd_set_close_on_exec, _dbus_strerror_from_errno, _dbus_warn, _DBUS_ZERO, DBUS_ERROR_FAILED, dbus_set_error, FALSE, NULL, TRUE.
void _dbus_print_backtrace(void)
On GNU libc systems, print a crude backtrace to stderr.
On other systems, print "no backtrace support" and block for possible gdb attachment if an appropriate environment variable is set.
Referenced by _dbus_abort.
dbus_bool_t _dbus_become_daemon(const DBusString *pidfile, DBusPipe *print_pid_pipe, DBusError *error, dbus_bool_t keep_umask)
Does the chdir, fork, setsid, etc.
to become a daemon process. pidfile NULL, or pidfile to create print_pid_pipe pipe to print daemon's pid to, or -1 for none error return location for errors keep_umask TRUE to keep the original umask FALSE on failure to become a daemon process. pidfile NULL, or pidfile to create print_pid_pipe file descriptor to print daemon's pid to, or -1 for none error return location for errors keep_umask TRUE to keep the original umask FALSE on failure
References _dbus_assert_not_reached, _dbus_error_from_errno, _dbus_getenv, _dbus_write_pid_to_file_and_pipe, DBUS_ERROR_FAILED, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error, FALSE, DBusError::message, NULL, TRUE.
dbus_bool_t _dbus_verify_daemon_user(const char *user)
Verify that after the fork we can successfully change to this user.
user the username given in the daemon configuration TRUE if username is valid
References _dbus_get_user_id_and_primary_group, _dbus_string_init_const, NULL, TRUE.
dbus_bool_t _dbus_change_to_daemon_user(const char *user, DBusError *error)
Changes the user and group the bus is running as.
user the user to become error return location for errors FALSE on failure
References _dbus_error_from_errno, _dbus_get_user_id_and_primary_group, _dbus_string_init_const, _dbus_warn, DBUS_ERROR_FAILED, dbus_set_error, FALSE, NULL, TRUE.
dbus_bool_t _dbus_write_pid_to_file_and_pipe(const DBusString *pidfile, DBusPipe *print_pid_pipe, dbus_pid_t pid_to_write, DBusError *error)
Writes the given pid_to_write to a pidfile (if non-NULL) and/or to a pipe (if non-NULL).
Does nothing if pidfile and print_pid_pipe are both NULL. pidfile the file to write to or NULL print_pid_pipe the pipe to write to or NULL pid_to_write the pid to write out error error on failure FALSE if error is set
Referenced by _dbus_become_daemon.
dbus_bool_t _dbus_command_for_pid(unsigned long pid, DBusString *str, int max_len, DBusError *error)
Get a printable string describing the command used to execute the process with pid.
This string should only be used for informative purposes such as logging; it may not be trusted.The command is guaranteed to be printable ASCII and no longer than max_len. pid Process id str Append command to this string max_len Maximum length of returned command error return location for errors FALSE on error
References _dbus_close, _dbus_error_from_errno, _dbus_read, _dbus_string_append_printf, _dbus_string_copy, _dbus_string_free, _dbus_string_init, dbus_set_error, FALSE, NULL, TRUE.
void _dbus_set_signal_handler(int sig, DBusSignalHandler handler)
Installs a UNIX signal handler.
sig the signal to handle handler the handler Installs a UNIX signal handler. sig the signal to handle handler the handler
References NULL.
dbus_bool_t _dbus_user_at_console(const char *username, DBusError *error)
Checks if user is at the console.
username user to check error return location for errors TRUE is the user is at the consolei and there are no errors
References _dbus_concat_dir_and_file, _dbus_file_exists, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, FALSE.
Referenced by _dbus_is_console_user.
void _dbus_init_system_log(dbus_bool_t is_daemon)
void _dbus_system_log(DBusSystemLogSeverity severity, const char *msg,...)
Log a message to the system log file (e.g.
syslog on Unix). severity a severity value msg a printf-style format string
References _dbus_system_logv.
void _dbus_system_logv(DBusSystemLogSeverity severity, const char *msg, va_list args)
Log a message to the system log file (e.g.
syslog on Unix). severity a severity value msg a printf-style format string args arguments for the format string If the FATAL severity is given, this function will terminate the program with an error code.
Referenced by _dbus_system_log.
dbus_bool_t _dbus_get_autolaunch_address(const char *scope, DBusString *address, DBusError *error)
Returns the address of a new session bus.
If successful, returns TRUE and appends the address to address. If a failure happens, returns FALSE and sets an error in error. scope scope of autolaunch (Windows only) address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
References _dbus_assert, _dbus_check_setuid, _dbus_get_local_machine_uuid_encoded, _dbus_getenv, _DBUS_N_ELEMENTS, _dbus_string_free, _dbus_string_init, DBUS_ERROR_FAILED, DBUS_ERROR_NOT_SUPPORTED, dbus_set_error_const, FALSE, NULL, TRUE.
dbus_bool_t _dbus_lookup_session_address(dbus_bool_t *supported, DBusString *address, DBusError *error)
Determines the address of the session bus by querying a platform-specific method.
The first parameter will be a boolean specifying whether or not a dynamic session lookup is supported on this platform.If supported is TRUE and the return value is TRUE, the address will be appended to address. If a failure happens, returns FALSE and sets an error in error.If supported is FALSE, ignore the return value. supported returns whether this method is supported address a DBusString where the address can be stored error a DBusError to store the error in case of failure TRUE on success, FALSE if an error happened
References FALSE, TRUE.
dbus_bool_t _dbus_read_local_machine_uuid(DBusGUID *machine_id, dbus_bool_t create_if_not_found, DBusError *error)
Reads the uuid of the machine we're running on from the dbus configuration.
Optionally try to create it (only root can do this usually).On UNIX, reads a file that gets created by dbus-uuidgen in a post-install script. On Windows, if there's a standard machine uuid we could just use that, but I can't find one with the right properties (the hardware profile guid can change without rebooting I believe). If there's no standard one we might want to use the registry instead of a file for this, and I'm not sure how we'd ensure the uuid gets created. machine_id guid to init with the machine's uuid create_if_not_found try to create the uuid if it doesn't exist error the error return FALSE if the error is set
References _dbus_append_user_from_current_process, _dbus_generate_uuid, _dbus_read_uuid_file, _dbus_sha_compute, _dbus_string_append, _dbus_string_free, _dbus_string_init, _dbus_string_init_const, _dbus_string_tolower_ascii, _dbus_write_uuid_file, DBusGUID::as_uint32s, dbus_error_free, DBUS_ERROR_NO_MEMORY, dbus_set_error, FALSE, NULL, TRUE.
Referenced by dbus_internal_do_not_use_get_uuid.
dbus_bool_t _dbus_threads_init_platform_specific(void)
Initialize threads as in dbus_threads_init_default(), appropriately for the platform.
FALSE if no memory
References _dbus_check_setuid, FALSE, TRUE.
Referenced by dbus_threads_init.
void _dbus_threads_lock_platform_specific(void)
Lock a static mutex used to protect _dbus_threads_init_platform_specific().
References _dbus_assert.
Referenced by dbus_threads_init.
void _dbus_threads_unlock_platform_specific(void)
Undo _dbus_threads_lock_platform_specific().
References _dbus_assert.
Referenced by dbus_threads_init.
unsigned long _dbus_pid_for_log(void)
The only reason this is separate from _dbus_getpid() is to allow it on Windows for logging but not for other purposes.
process ID to put in log messages
References _dbus_getpid, FALSE, NULL, TRUE.
Referenced by _dbus_abort, _dbus_real_assert, _dbus_real_assert_not_reached.
DBUS_PRIVATE_EXPORT dbus_pid_t _dbus_getpid(void)
Gets our process ID.
process ID
Referenced by _dbus_append_user_from_current_process, _dbus_credentials_add_from_current_process, _dbus_pid_for_log.
DBUS_PRIVATE_EXPORT dbus_uid_t _dbus_getuid(void)
Gets our UID.
process UID Gets our UID.on Windows, just DBUS_UID_UNSET
References DBUS_UID_UNSET.
DBUS_PRIVATE_EXPORT void _dbus_flush_caches(void)
Called when the bus daemon is signaled to reload its configuration; any caches should be nuked.
Of course any caches that need explicit reload are probably broken, but c'est la vie.
References _dbus_user_database_flush_system.
const char* _dbus_replace_install_prefix(const char *configure_time_path)
DBusRLimit* _dbus_rlimit_save_fd_limit(DBusError *error)
dbus_bool_t _dbus_rlimit_raise_fd_limit_if_privileged(unsigned int desired, DBusError *error)
dbus_bool_t _dbus_rlimit_restore_fd_limit(DBusRLimit *saved, DBusError *error)
void _dbus_rlimit_free(DBusRLimit *lim)
DBUS_PID_UNSET
an invalid PID used to represent an uninitialized dbus_pid_t field
Referenced by _dbus_credentials_new, _dbus_credentials_include, _dbus_credentials_are_superset, _dbus_credentials_are_empty, _dbus_credentials_add_credential, _dbus_credentials_clear, _dbus_credentials_to_string_append, _dbus_transport_get_unix_process_id.
DBUS_UID_UNSET
an invalid UID used to represent an uninitialized dbus_uid_t field
Referenced by dbus_bus_get_unix_user, _dbus_credentials_new, _dbus_credentials_include, _dbus_credentials_are_superset, _dbus_credentials_are_empty, _dbus_credentials_are_anonymous, _dbus_credentials_add_credential, _dbus_credentials_clear, _dbus_credentials_to_string_append, _dbus_check_dir_is_private_to_user, _dbus_user_info_fill, _dbus_append_keyring_directory_for_credentials, _dbus_stat, _dbus_getuid, _dbus_user_database_lookup_group, _dbus_user_database_lookup, _dbus_user_database_get_username.
DBUS_GID_UNSET
an invalid GID used to represent an uninitialized dbus_gid_t field
Referenced by _dbus_check_dir_is_private_to_user, _dbus_stat, _dbus_user_database_lookup_group, _dbus_user_database_get_groupname.
DBUS_PID_FORMAT
an appropriate printf format for dbus_pid_t
Referenced by _dbus_credentials_to_string_append.
DBUS_UID_FORMAT
an appropriate printf format for dbus_uid_t
Referenced by _dbus_credentials_to_string_append, _dbus_is_console_user, _dbus_user_database_lookup.
DBUS_GID_FORMAT
an appropriate printf format for dbus_gid_t
Referenced by _dbus_check_dir_is_private_to_user, _dbus_user_database_lookup_group.
DBUS_SOCKET_FORMAT
DBUS_SOCKET_INIT
DBUS_POLLABLE_FORMAT
_DBUS_POLLIN
There is data to read.
Referenced by _dbus_poll.
_DBUS_POLLPRI
There is urgent data to read.
_DBUS_POLLOUT
Writing now will not block.
Referenced by _dbus_poll.
_DBUS_POLLERR
Error condition.
Referenced by _dbus_poll.
_DBUS_POLLHUP
Hung up.
_DBUS_POLLNVAL
Invalid request: fd not open.
DBUS_VA_COPY
_DBUS_BYTE_OF_PRIMITIVE
Casts a primitive C type to a byte array and then indexes a particular byte of the array.
_DBUS_DOUBLES_BITWISE_EQUAL
On x86 there is an 80-bit FPU, and if you do "a == b" it may have a or b in an 80-bit register, thus failing to compare the two 64-bit doubles for bitwise equality.
So this macro compares the two doubles bitwise.
DBUS_DEFAULT_MESSAGE_UNIX_FDS